In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("./test_dataset.csv")

In [3]:
df

Country   Age   Salary  Purchased
0        USA  25.0  50000.0       True
1     Canada   NaN  60000.0      False
2    Germany  35.0      NaN       True
3  Australia  28.0  55000.0      False
4      India  45.0      NaN       True
5         UK   NaN  62000.0      False
6      Japan  32.0  58000.0       True
7     France  29.0      NaN      False
8     Brazil   NaN  75000.0       True
9     Mexico  41.0  54000.0      False

In [4]:
x = df[["Country","Age","Salary"]].values

In [5]:
x

array([['USA', 25.0, 50000.0],
       ['Canada', nan, 60000.0],
       ['Germany', 35.0, nan],
       ['Australia', 28.0, 55000.0],
       ['India', 45.0, nan],
       ['UK', nan, 62000.0],
       ['Japan', 32.0, 58000.0],
       ['France', 29.0, nan],
       ['Brazil', nan, 75000.0],
       ['Mexico', 41.0, 54000.0]], dtype=object)

In [6]:
y = df[["Purchased"]].values

In [7]:
y

array([[ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False]])

In [8]:
from sklearn.impute import SimpleImputer

In [11]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [12]:
imputer = imputer.fit(x[:,1:3])

In [13]:
x[:,1:3]=imputer.transform(x[:,1:3])

In [14]:
x

array([['USA', 25.0, 50000.0],
       ['Canada', 33.57142857142857, 60000.0],
       ['Germany', 35.0, 59142.857142857145],
       ['Australia', 28.0, 55000.0],
       ['India', 45.0, 59142.857142857145],
       ['UK', 33.57142857142857, 62000.0],
       ['Japan', 32.0, 58000.0],
       ['France', 29.0, 59142.857142857145],
       ['Brazil', 33.57142857142857, 75000.0],
       ['Mexico', 41.0, 54000.0]], dtype=object)

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
label_encoder_x = LabelEncoder()

In [17]:
x[:,0] = label_encoder_x.fit_transform(x[:,0])

In [18]:
x

array([[9, 25.0, 50000.0],
       [2, 33.57142857142857, 60000.0],
       [4, 35.0, 59142.857142857145],
       [0, 28.0, 55000.0],
       [5, 45.0, 59142.857142857145],
       [8, 33.57142857142857, 62000.0],
       [6, 32.0, 58000.0],
       [3, 29.0, 59142.857142857145],
       [1, 33.57142857142857, 75000.0],
       [7, 41.0, 54000.0]], dtype=object)

In [19]:
from sklearn.preprocessing import OneHotEncoder

In [20]:
oneHotEncoder = OneHotEncoder()

In [22]:
x=oneHotEncoder.fit_transform(df.Country.values.reshape(-1,1)).toarray()

In [23]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

In [24]:
label_encoder_y = LabelEncoder()

In [25]:
y = label_encoder_y.fit_transform(y)

/home/ammad/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [26]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [29]:
x_train

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [30]:
x_test

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
y_test

array([1, 1])

In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
sc_x = StandardScaler()

In [34]:
x_train = sc_x.fit_transform(x_train)

In [35]:
x_test = sc_x.transform(x_test)

In [36]:
x_train

array([[-0.37796447,  0.        , -0.37796447, -0.37796447,  0.        ,
         2.64575131, -0.37796447, -0.37796447, -0.37796447, -0.37796447],
       [-0.37796447,  0.        , -0.37796447, -0.37796447,  0.        ,
        -0.37796447, -0.37796447,  2.64575131, -0.37796447, -0.37796447],
       [-0.37796447,  0.        ,  2.64575131, -0.37796447,  0.        ,
        -0.37796447, -0.37796447, -0.37796447, -0.37796447, -0.37796447],
       [-0.37796447,  0.        , -0.37796447, -0.37796447,  0.        ,
        -0.37796447,  2.64575131, -0.37796447, -0.37796447, -0.37796447],
       [-0.37796447,  0.        , -0.37796447,  2.64575131,  0.        ,
        -0.37796447, -0.37796447, -0.37796447, -0.37796447, -0.37796447],
       [ 2.64575131,  0.        , -0.37796447, -0.37796447,  0.        ,
        -0.37796447, -0.37796447, -0.37796447, -0.37796447, -0.37796447],
       [-0.37796447,  0.        , -0.37796447, -0.37796447,  0.        ,
        -0.37796447, -0.37796447, -0.37796447

In [37]:
x_test

array([[-0.37796447,  0.        , -0.37796447, -0.37796447,  1.        ,
        -0.37796447, -0.37796447, -0.37796447, -0.37796447, -0.37796447],
       [-0.37796447,  1.        , -0.37796447, -0.37796447,  0.        ,
        -0.37796447, -0.37796447, -0.37796447, -0.37796447, -0.37796447]])